package io.intellixity.nativa.persistence.authoring;

import java.util.Map;

public record FieldDef(
    TypeRef type,
    boolean nullable,
    boolean key,
    /** If true, the backend may auto-generate the value (e.g. identity/sequence/_id). */
    boolean autoGenerated,
    /** Additional attributes (generic, backend-agnostic). */
    Map<String, Object> attrs
) {
  public FieldDef {
    attrs = attrs == null ? Map.of() : Map.copyOf(attrs);
  }

  public FieldDef(TypeRef type, boolean nullable, boolean key) {
    this(type, nullable, key, false, Map.of());
  }

  public FieldDef(TypeRef type, boolean nullable, boolean key, boolean autoGenerated) {
    this(type, nullable, key, autoGenerated, Map.of());
  }
}

